### ISSUE TITLE
document and implement error codes

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#122]
Error Name | Error Code | Error Description
-- | -- | --
Connect | 1001 | unable to connect to the server (network)
Credentials | 1002 | unable to authenticate to the server
  |   | when background uploading stops / restart? partial upload?
  |   | incorrect login / pw

**Comment by foundscapes** [comment]
@hiromipaw @tladesignz these should have been integrated already and added to for the new designs. Do we now have a comprehensive error list?

**Comment by tladesignz** [comment]
Sorry, since this is only a rudimentary described issue, I don't get the full intention. I can't find any of these strings and numbers in the source code, so there's probably nothing implemented.

There is no comprehensive error list, as the number of potential errors is potentially indefinite, can come from different parts of the underlying software stack (e.g. HTTP errors, TLS errors, TCP/IP errors, DNS errors and on and on...), will change over time and is different by manufacturers.

There are only 2 strategies in my opinion:

1. The good one:
- Identify the ones where *actual users* struggle the most (**NOT** the ones which testers see the most often because they're easy to produce), and do special UI for them, which *really* explains the problem and a strategy to solve it.
- Show system provided error messages in all other cases.

-> This gives the biggest bang for the buck and makes it easiest to assist users with getting at the core of the problem.

Drawback: Not localized, more or less confusing technobabble for non-techy users.

2. The bad one:
- Show insubstantial messages (like e.g. "unable to connect") for a few different error classes.

-> Will be nicely localized and users don't see words they don't understand.

Drawback: Doesn't give a solution, disguises underlying problems, inhibits the user from googling self help and thwarts user support.

**Comment by hiromipaw** [comment]
@tladesignz I think I'll take a middle way in your approach 1. I.e. Handle errors returned from the backends we implement in order to give users more meaningful error messages.

I think next cloud has error codes, we could identify the set that the user is more likely to encounter and handle those if we don't do that already so that we can return a more meaningful message to the user beyond "unable to connect".

**Comment by hiromipaw** [comment]
I think we can revisit this at some later stage, after the update has been completed and with some crash data at hand.
