### ISSUE TITLE
App crashed when adding item to queue that was uploading

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#173]
Phone: Moto G
OS: Android 5.1
Server: GoodCloud

1. Upload 5 files to goodcloud folder
2. add 2 files to upload in batch
3. one begins to upload
4. App crashes

Could not reproduce, will add if happens again

**Comment by foundscapes** [comment]
Phone: Galaxy S7
OS: Android 3.2.49
Server: GoodCloud


    Upload 4 files to goodcloud folder
    add 2 files to upload in batch
    zero files upload

closed app, reopened, 3 mins later all had uploaded

**Comment by roseregina** [comment]
Phone: Galaxy S7
OS: Android 8.0.0
Server: GoodCloud

I can't tell if this is the same bug, but I am having a lot of problems/ inexplicable irregularities with uploading files (affects both images and videos), and aside from the initial add, it has been while there were already images in the queue. 

A couple of times, I was been able to get progress on the uploads by force quitting and reopening save, but this has not consistently worked. 

The Uploads list displays multiple files, all at 0%, initially a mix of "Uploading" and "Waiting", but after force quitting and restarting several times, it got down to just "Uploading" with four images in queue.  The percent indicator moved sporadically, but I was not able to tell if it was accurate and the problem was entirely with the upload.

**Comment by roseregina** [comment]
0.2.2-beta-7 
The Good Cloud

Fine on **MotoG** and **Pixel3a** (added a few photos, added more while they were uploading, all photos uploaded without problem). 

On the **GalaxyS7**, I queued 3 images, then added another 4. The first 5 uploaded fine, but it's been hung on the last two for maybe a half hour. Interestingly, when I went to upload the screenshots via Dropbox in the app, those screenshots are marked as waiting. I was able to kick start the uploads again after force quitting through Android settings twice. 

On the upside, the percentage indicator on the Uploads screen seems to be working better now.

**Comment by roseregina** [comment]
I triggered this kind of hang while looking for a way to pause the upload in #124 by swiping upward on the Uploads screen. 

I could not "unpause" and resume through the UX interface, but it did appear to resume after I force quit the app through Settings > Apps.

**Comment by foundscapes** [comment]
please test with 0.2.3-BETA-1
