### ISSUE TITLE
Edit Screen: make text on right same size as left

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#184]
On all devices, beta-2

edit Screen: make text on right (upload) same size as left (preview)

![RightLeftSizingS7](https://user-images.githubusercontent.com/2231711/71025524-0ea73100-20bc-11ea-878a-9a2f8d0387f0.jpg)

upload screen: and for Uploads / Done
![RightLeftSizing1S7](https://user-images.githubusercontent.com/2231711/71025536-16ff6c00-20bc-11ea-869e-9c6ef234a3a0.jpg)

and wherever else it is (still hunting)

**Comment by foundscapes** [comment]
0.2.2-beta-3 
Looks ok on Moto-G, s7. 3av - can we make them both mixed case? @n8fr8

**Comment by roseregina** [comment]
0.2.2-beta-7
GalaxyS7 (also tested on Pixel3a and MotoG, but did not post images)

The font for "Preview" and "Upload" are the same size and both are mixed case. 

I can't tell if it's from staring at it for too long or because "Upload" goes below the line, but "Preview" doesn't, but I had to check with super imposing lines to see that they were actually the same size. 
![image](https://user-images.githubusercontent.com/15040203/72214284-a0d00880-34b3-11ea-8e40-0e83ff1d6a38.png)
