### ISSUE TITLE
Uploads don't pause anymore in edit mode

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#203]
phones: Pixel 3a, samsung galaxy S7, motoG

server: oademo.thegood.cloud

all kept going

**Comment by n8fr8** [comment]
there was a bug in stop/starting the upload service. next build has fix.

**Comment by foundscapes** [comment]
awesome, we'll test asap!

**Comment by roseregina** [comment]
Save 0.2.2-RC-1

Dropbox server (rr's personal account) and Good Cloud server

GalaxyS7: 
Pause works as expected 

MotoG: 
1. Upload multiple files
2. Click on circled number to go to Uploads view
3. Click "Edit" in upper right corner
4. **Expected result** upload pauses 
  **Actual result** some of the time (maybe half), it behaves as expected, but the other half of the time, the app crashes to the main android screen. 


**EDIT:** Just had app crash on the GalaxyS7 when clicking on edit button

**Comment by n8fr8** [comment]
didn't test pause as much with Dropbox, so will see if there is an issue there.

**Comment by foundscapes** [comment]
Save version: 0.2.3-BETA-1
phone: Pixel 3a
OS: android 10
server: oademo.thegood.cloud

3 images paused as expected when hitting "edit" all uploaded as expected.

@roseregina please test this with 0.2.3-BETA-1 on dropbox and IA

**Comment by roseregina** [comment]
Save version: 0.2.3-BETA-1
phone: GalaxyS7
OS: android 8.0.0 w/ Samsung Experience 9.0 
server: Dropbox

I think the "edit" is working to pause for this combo. I want to test with other phone and server combos, as well as rechecking this because I had some unexpected, but I believe unrelated, behaviours that made it trickier to tell what exactly what happening.
