### ISSUE TITLE
Make sure PGP public key is shared via proofmode

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#208]

**Comment by n8fr8** [comment]
this is done and will be in next build

**Comment by foundscapes** [comment]
@n8fr8 

Save 0.2.3.BETA-2
Phone: Pixel3a
OS: Android 10
Sever: DropBox
Orbot Disabled
Proofmode Enabled

1.  Delete Orbot
2. Open Save
3. connect / login to DropBox
4. Enable Proofmode
5. Browse existing/ chose folder
6. selected 3 images
7. successfully uploaded
8. @n8fr8 - checked and files are in dropbox folder but I don't see a pgp key in the json file (copied here:)
{"collectionId":5,"contentLength":3904995,"createDate":"May 11, 2020 2:12:06 PM","flag":false,"mediaHashBytes":[],"mediaHash":"31da71d3819411084c8a68456ba8fe9b95220a65438b5799b22fc0285c2581c5","mimeType":"image/jpeg","originalFilePath":"file:///data/user/0/net.opendasharchive.openarchive.release/cache/20200511_141206.JPEG_20200511_141201.jpg","priority":1,"progress":3904995,"projectId":3,"selected":false,"serverUrl":"/ncpixel3a/2020-05-11T14:12:06GMT-07:00/JPEG_20200511_141201.jpg","status":5,"title":"JPEG_20200511_141201.jpg","updateDate":"May 11, 2020 2:12:06 PM","uploadDate":"May 11, 2020 2:12:08 PM","id":13}

**Comment by n8fr8** [comment]
Sorry, what I meant was done is the option to share your PGP key from the OpenArchive app. That part is right. You are correct that we are not yet uploading the PGP key along side the proof metadata files. That still needs to be done.

**Comment by foundscapes** [comment]
OK - Does the app generate the key or do people have to login with it somehow?

**Comment by n8fr8** [comment]
The app generates it, and uses to sign the data... see the ".asc" files that get uploaded with the proof. Those are the PGP signatures.

Then under the "Metadata" setting in Save, you can now see the "ProofMode Identity - Share ProofMode Public Key". That is where you are meant to tap to manually share the PGP key the app has generated with you, via email, Signal, etc. 

I will add it to the files to be uploaded as well now, which will be easier.

**Comment by foundscapes** [comment]
That's what I thought, but wanted to make sure, thank you.

Ok great, let us know when to test!

**Comment by roseregina** [comment]
0.2.3.BETA-3
GalaxyS7
Dropbox

When upload one image with proof mode turned on, I get the following files: 
- 20200514_144131.jpg
- 20200514_144131.jpg.meta.json
- 20200514_144131.jpg.meta.json.asc
- 20200514_144131.jpg.meta.json.proof.csv
- 20200514_144131.jpg.meta.json.proof.csv.asc

Further, while  _**Save**_ was listed as an option to share the key from the Metadata settings, I was not able to actually make that work (separate issue).

**Comment by roseregina** [comment]
0.2.3.BETA-3
Pixel3a
OA Good Cloud

This is probably a separate issue, but fairly minor and found while checking on the key: 

Here is the signature for a file @foundscapes uploaded: 
`-----BEGIN PGP SIGNATURE-----
Version: BCPG v@RELEASE_NAME@

iQIcBAADCAAGBQJevbcOAAoJEHjIXy2IJLZEhZ8P/05LRZU23zCiK6jjngVdE5Ow
FATbh1O/qeTyhgRwXscWaTEUy9p6pTabHVxGOW+/hw5DAZ7FLGDwevgveMF/jj6g
ZMKuKiQ6xJbzuY4leUOqVNnxmVET9Z7dCgdz22L+Z0CTOtbcmVAHKQVBXPaG+Q7s
lgKumcnYe091CL8txEy1L2yKS05wtC2KX55s0sjmGM915CBzU7YNN1Oem77aKb2R
Voi7aTKlYEyXHc2lAbhkQIAjJTV+1N3ZJjEPatzjY21hQbS/TqtXKPT2M0Oy16kZ
0j5Qakd6NJt2givi48LSDJ5aNp6w1AGUMWRkI7XwrtU7Bf/vfrhQgdTJ5X5fkO1y
4rrraqne2HEGKj33TRjlU6hpiSv8ld/75EH9PFYaaX3ec0L1kxtMEqihO9g0sz0V
xGANU+c60awJAZeaXLpcEI8rnZNZDsK6O5OG2ypEL3O1Bx1FJEdbId4+REGLQ8m3
GnsMv6k8EH1CbVgq3h8dm8ibvkK/cQS5mnl2Ma7DkoStDduBdDXesT9LUA7mSO6M
98ETxskBAmhoUcRpavB3UMEm5AghmcsptVl0bDojxiEGXYgx36B2ctcL1gVBieZO
pMLUdGDopwBtiqMlOoQwcL5/36MXhH8XTHgjDeo2GZtKTevZYAEZEJc/pUMWx7RS
SpOoGXtbfRDW/RbwXUW7
=tisD
-----END PGP SIGNATURE-----`

Shouldn't `v@RELEASE_NAME@`be actual information instead of a placeholder?

**Comment by foundscapes** [comment]
This is working now, but leaving open so @n8fr8 can check on the placeholder info

**Comment by n8fr8** [comment]
fixing that will require an update to the core ProofMode library. Will move this ticket to the "future coolness" milestone. 

thanks for testing!

**Comment by elric-wamugu** [comment]
Confirmed to be working. Tested on Google Pixel 4a with Android 11
