### ISSUE TITLE
Add TorServices support integration 

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#258]
integrate TorServices instead of using Orbot
https://github.com/guardianproject/tor-android

This allows for easy use of Tor without a separate app.

**Comment by johnhess** [comment]
@tladesignz does our discussion earlier mean that this is not the pivot to make (and instead, stay with Orbot until maybe Tor VPN supercedes it)?

if so, feel free to close this.

**Comment by tladesignz** [comment]
Well, there's a push to have Tor in as much apps as possible.
I think on Android, it's easier to have a built-in Tor coexist with Orbot. (But please talk to Nate about how that works.)
It's definitely easier for the user, because they don't have to download another app.
Not sure about the Play Store China situation, though. (Again, talk to Nate.)

**Comment by n8fr8** [comment]
Save on Android isn't distributed in Chinese app stores (and likely wouldn't able to be), so integrating Tor directly is not a problem.

Also, yes, Tor in Save can coexist with Orbot just fine. No need to wait for future Tor VPN either.

OnionShare shows how this is possible to do:
https://github.com/onionshare/onionshare-android

Ultimately, if "Archive media over Tor" is going to remain a key marketing point of Save, it should be integrated directly.

**Comment by johnhess** [comment]
Let's have our new designer spec out the UX/interactions for this across both apps, then implement.

**Comment by foundscapes** [comment]
Keep this open in case Orbot is sunsetted
