### ISSUE TITLE
Nothing happens when we click on Sign in with Google for adding Internet Archive server on Save App

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#267]
Summary : When we try to add Internet Archive Server and click on Sign in with Google, nothing happens.

1. Go to Save App
2. Click on + icon to add the server
3. Click on Internet Archieve
4. Click on Acquire Keys
5. Click on Sign in with Google

**Expected behavior**
User should be able to get the Google Credentials login pop up

Actual Result  : 
Nothing happens when we click on Sign in with Google

Below is the video link : 
https://drive.google.com/file/d/1GNW8g1RyD9NR-elylhlkJLeA4Ty22-fk/view?usp=sharing

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A70
 - App Version : 0.2.4-RC-2

**Comment by n8fr8** [comment]
Sign in with Google on the Internet Archive is definitely a new feature. Hmmm.... Need to think how to support that.

**Comment by ozgegn** [comment]
Hi @n8fr8 ,
Is this something we should search ?

**Comment by johnhess** [comment]
Regardless of using Google's SSO, clicking "Acquire Keys" does nothing for me [on Android 11, A21].  The app just hangs and the OS asks if I want to wait or kill the app.

**Comment by tladesignz** [comment]
Google disabled the ability to use "Sign in with Google" in embedded web view UIs. It also doesn't work on iOS:

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

We can't do anything about it, except explain the situation.

You can either
1. use a normal login inside the app-embedded web view, then Save will be able to scrape the access and secret keys.
2. use a Google login in a browser and copy-paste the keys from there manually.

**Comment by tladesignz** [comment]
For reference, this is how it looks now:

![Simulator Screen Shot - iPhone SE1 @ iOS 15 - 2022-04-08 at 13 56 13](https://user-images.githubusercontent.com/117089/162430916-84a980d5-0d90-4bf1-bd65-72f24a25fa95.png)

(Same on Android. You don't even see the button anymore, because some library is now already blocked to load by the Google servers in this circumstances which results in that error message. A little better than a non-functioning button, but not much. 😕)

**Comment by tladesignz** [comment]
For reference: This is what we currently show on iOS:

![Simulator Screen Shot - iPhone SE1 @ iOS 15 - 2022-04-08 at 13 58 29](https://user-images.githubusercontent.com/117089/162431183-9af5f923-ea7f-4d18-b17a-a85d4a0a26e0.png)

Android only shows this text between the key entry fields and the "Acquire Keys" button:

> Save nees your Internet Archive account's API keys to be able to upload it.

On iOS, when you tap the middle paragraph, you're forwarded to the system browser.

Pretty sure this UI can be improved. I suggest looping in a UX designer to improve the situation and then adapt the Android and iOS version at the same time.

**Comment by johnhess** [comment]
Gotcha, I'd assumed it was something misbehaving, rather than WAI.

I don't mind getting a UX designer involved, but we may need to bring some information to the table about what options there are to authenticate and/or upload to IA.  Can you do a bit of digging and add information on this ticket?

**Comment by tladesignz** [comment]
Here's the Internet Archive's documentation about its API:
https://github.com/vmbrasseur/IAS3API

To my knowledge, there's no API to create accounts or the like, and no other facilities and libraries for authentication than these API access keys.

So, there's these 2 options:

1. Use a browser, log in, go to that page which shows you the keys and copy-paste that into our app.
2. Let the app try to scrape them. For that you need to log in. You won't be able to do that with Google credentials, because Google doesn't allow that.

A UX redesign would solely be about explaining the situation better to the user. 

Of course I didn't look at IA in a long time, so there might be some changes I missed. Happy to implement something else, if you can come up with another way!
