### ISSUE TITLE
Connect Your Space screen should be displayed when we remove dropbox id from the app and if the user do not have any other space logged in

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#278]
When we connect using only dropbox and no other spaces and then remove the dropbox id from app, it should show us the "Connect Your Space" screen only as there are no other spaces. Instead , the app is not refreshed and the dropbox id which was removed from the app is only shown. When we go to the Project space and then come back again, the dropbox id disappears but still the other details related to the dropbox screen remains.

**To Reproduce**
1. Go to Save App.
2. Click on + icon to go to Connect Your Space screen
3. Select drop box and connect to the dropbox id
4. Again click on dropbox id and click on Remove from App

 Expected behavior : 
As there are no other space created, once the user removes the dropbox id from App, it should redirect user to connect your space screen 

Actual Result : 
Even after removing the dropbox id from app, the app is not refreshing and not redirected to connect your space screen. Instead it is redirected to dropbox screen only with the removed user id still visible

Below is the video link : 

https://drive.google.com/file/d/1-XzVu8o_SgzrGcpNeXMj6KaBzWXi3B9_/view?usp=sharing

  Environment : 
 - OS version: Android 11
 - Device: Samsung Galaxy M32
 - App Version : Save 0.2.3-BETA-3

**Comment by tladesignz** [comment]
What I implemented on iOS is, that the UI updates correctly when state changes - Even when there's no space anymore.

Then, when the user wants to jump into any activity, e.g. to create a project, add a file, work on settings etc. it's always the same logic:

- Check, if a space exists. 
  - Set first space selected, if none selected, yet.
  - If no space exists, jump user to space creation workflow.
- Check, if project exists.
  - Set first project selected, if none selected, yet.
  - If no project exists, jump user to project creation workflow.
- If space and project is ok, allow user to continue with what they wanted to do.

This, for one allows the user to have a small look around, before handing over any credentials.

It's also important, because Apple wants apps to have as much functionality as possible without any account creation. That may not apply here so much, but nevertheless, it's a good practice.

**Comment by purvi-ranawat** [comment]
It works fine for Save 0.2.4-RC-6-3ba7fdb

**Comment by johnhess** [comment]
[Release](https://github.com/OpenArchive/Save-app-android/tree/0.2.4-RC-6) sent to internal testing [download APK](https://play.google.com/apps/test/net.opendasharchive.openarchive.release/20436)
