### ISSUE TITLE
Create New Android Release

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#281]
@tladesignz Can you create a test release for @purvi-ranawat to thoroughly test this milestone's CUJ on?  Since the last play store release in 2020, there have been some fixes.  I also want to make sure we catch any regressions introduced in e.g. the Kotlin migration before we give this milestone the "all clear".

**Comment by n8fr8** [comment]
I have the release key for Android, so it has to be me, for now.

**Comment by johnhess** [comment]
Do we need the release key for a test release?  I thought those could be unsigned.

If we do, what's your preference is in terms of key security vs. workload?  I'd be happy to raise the "bus factor" and would like to be able to fire out a release on demand.

**Comment by tladesignz** [comment]
> Do we need the release key for a test release? I thought those could be unsigned.

They try to move you over to resigning, but we're trying to stay with the old system because that means nobody needs to trust Google.

However, even for the new process where Google repacks and resigns your apps, you'll need a release key AFAIR.

> If we do, what's your preference is in terms of key security vs. workload? I'd be happy to raise the "bus factor" and would like to be able to fire out a release on demand.

For that, the private key needs to be shared. Either by really sharing it, or by setting up a machine which is the key owner and can be used for signing by multiple people.

**Comment by johnhess** [comment]
@n8fr8 can you post that QA build?

**Comment by johnhess** [comment]
0.2.4-RC-5: https://play.google.com/apps/test/net.opendasharchive.openarchive.release/20435
