### ISSUE TITLE
No error message is displayed if we have tried uploading the media with more size than the available size on the space

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#319]
Precondition : Available space on the server should be lesser than the size of the media getting uploaded

Steps to reproduce the behavior : 
1. Go to Save App
2. Connect to the space which has lesser size than the media getting uploaded
3. Select the media of more size and click on Upload

Expected behavior
Error message stating that the server does not have the space required

Actual Result : 

No Error message is displayed if the server have the space lesser than the size of the media. Instead it shows as processing and just displayed the %age of media uploaded.Also, if the space is not available, the %age of media uploaded remains at the same %age but no error message is displayed

Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy M32
 - App Version : 0.2.4-RC-6

**Comment by purvi-ranawat** [comment]
Still message is not displayed it keeps on processing. 
Tested on Samsung A13, Samsung A 12. 
App Version: Save 0.2.4-RC-14-1837D48

**Comment by pkhivesara** [comment]
@purvi-ranawat Is this for NextCloud or Hetzner? Can you share a screenshot of what you are seeing?

**Comment by purvi-ranawat** [comment]
@pkhivesara I tried with dropbox. 



![Image](https://user-images.githubusercontent.com/8190141/185985463-11d65aec-2c7e-4863-bb5c-c3b9a105e377.jpeg)

**Comment by johnhess** [comment]
IIRC, when we last spoke, @pkhivesara shared that there isn't a universal API among nextcloud/WebDAV providers to detect a failure to upload due to not having enough space on the server.  Hetzner uses nextcloud to power storage but doesn't provide the same APIs that e.g. GoodCloud did/would.  (Investigation was issue #357 )

As a next step, we discussed adding an error message for the user upon an HTTP 400 (IIRC, the code we're getting when we can't upload due to space constraints).  We'd say "Unable to upload.  Is your server full?" or something to that effect.

Please comment here if I've left out important bits or misremembered.

**Comment by pkhivesara** [comment]
We are not receiving a 'code' for Hetzner unlike Nextcloud, where we call a separate API which helps us figure out the storage space. Hetzner does not have any such provisions, and nor does it provide us storage details or possible unique 'code' for upload failures.
