### ISSUE TITLE
Updating ProofMode integration

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#404]
We've updated our libProofMode-Android library and provided improved documentation and sample code here:
https://gitlab.com/guardianproject/proofmode/libproofmode-android-sample

In the new model, it is also expected that all the proofmode generated files, are stored in a zip archive file, which makes it easy to verify using new tools such as: https://proofcheck.gpfs.link/ and processes as described here: https://proofmode.org/verify

In addition, there is improved UX in the primary ProofMode app related to exposing, sharing, and prompting for specific permissions, that we can share and discuss.

Happy to assist in updating the code, or send a pull request with changes.

**Comment by hiromipaw** [comment]
@tladesignz let's see if by updating proofmode integration we can also solve https://github.com/OpenArchive/OA-Trail-of-Bits/issues/16

**Comment by tladesignz** [comment]
Ok, I updated ProofMode to the latest version 1.0.25. Besides minor API changes it still behaves exactly the same and produces the same output. Which is good. :-)

I currently feel very mixed about the ZIP file. If we switch to that, all the proofmode metadata gets hidden away in that ZIP. Of course easier to verify with that service, but since we're already a file handling service where every upload batch gets stored in a folder and every asset already has a sidecar file, having additional metadata in a ZIP file is an accessibility blocker for visual inspection.

Doing both seems the worst idea, since we would use double bandwidth.

Besides, it seems the lib actually doesn't put the original file in the ZIP, so the proof check wouldn't work like this. We would need to do that in Save code, actually, to make it work.

From my point of view, I would very much like to have it the other way round: That https://proofcheck.gpfs.link/ gets improved in a way, so it accepts drag-n-drop of multiple files resp. all the ProofMode files + the original file or even complete folders where every folder contains an asset plus the ProofMode files (+ additional files which shall be ignored.)

That's perfectly doable with modern browsers and would also give backwards compatibility.

Regarding UI/UX improvement, there's another ticket, where we should follow up that part: #337

**Comment by tladesignz** [comment]
While playing with the Proofcheck service, I start to feel, that this thing needs to become way more flexible. I couldn't just pack a ZIP from macOS' Finder containing the files and throw it at that service. It didn't accept it. Maybe because of naming conventions, maybe because files might have been nested in a subfolder?

**Comment by tladesignz** [comment]
@purvi-ranawat: To QA this, please test, if ProofMode works and provides 3 files: 2 GPG signatures and a CSV and all of them contain data which seems sensible.

Please test on all 3 services, to make sure I didn't break anything with the refactoring of duplicated code.

This fix will be contained in builds higher than 20525. Not planning to to release one this week, so keep in your backlog!

**Comment by purvi-ranawat** [comment]
@tladesignz  / @hiromipaw : 

Currently not able to test this because of the below issue : 

https://github.com/OpenArchive/Save-app-android/issues/422    (Not able to select any media for uploading)

**Comment by purvi-ranawat** [comment]
This is working fine.

When in proof mode, 5 extra files are generated for each uploaded file (".asc", ".proof.csv", ".proof.csv.asc", ".proof.json" and ".proof.json.asc")

Tested on the build version : 0.3.0-alpha5

Tested on Samsung Galaxy A70 (Android 11) and Samsung Galaxy A13 (Android 13)
