### ISSUE TITLE
Update save android to the latest libProofMode release.

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#424]
Update save android to the latest libProofMode release.

GP has new sample documentation on how to integrate it: https://proofmode.org/blog/integrating-proofmode-library

**Comment by tladesignz** [comment]
The latest version seems to be 1.0.25:

https://github.com/guardianproject/gpmaven/tree/master/org/witness/android-libproofmode

https://gitlab.com/guardianproject/proofmode/proofmode-android/-/blame/master/android-libproofmode/build.gradle#L75

That's where we're at already, because of #404:

https://github.com/OpenArchive/Save-app-android/blob/master/dependencies.gradle#L20

Let's continue tracking this in #404!
