### ISSUE TITLE
Uploading of Video option not available on Android phones

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#429]
**Describe the bug**
When we click on "+" icon for selecting the media, only photos are displayed. But even though videos are there on the phone, videos are not available for selection for uploading to the Save App.

1. Go to Save App
2. Select any server
3. Select / Create any folder and click on "+" icon  to select the media

**Expected behavior**
On clicking on "+" icon for selection of media, both photos and videos should be available for selection

Actual Result : 
Only photos are available for selection. Not able to see any videos for selection even though there are quite a few videos on the phone

**Environment (please complete the following information):**
 - OS version: Android 13
 - Device: Samsung Galaxy A13
 - App Version : 0.2.6

**Additional context**

**Comment by tladesignz** [comment]
You gotta love Android. Android 13 introduces a new video permission which you have to **ask for**, explicitly.

I added this. 

**However**...

- There's technically 2 permissions: `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO`.
- In the Android app permissions UI, they are shown as **one**, though.
- If you don't ask, you seem to get *image* automatically (seems sort of a fall back for buggy code) **but** not *video*.
- Now the fixed code comes along and tries to find out, if it needs to ask.
- Android says, "nope, all fine, you have permission for both".
- However, videos are not shown, because in fact, that wasn't authorized earlier.

Ugly workaround for users: Go to Android app settings for Save. Remove authorization for "images and video".
-> Now the app will ask and you can grant both.

🤦 ...as said: you gotta love Android...


Will be contained in next beta build / release.

Please keep in evidence for QA until then, @purvi-ranawat.

**Comment by purvi-ranawat** [comment]
@tladesignz  / @hiromipaw :  This is working as per the steps mentioned above by @tladesignz . But I am still keeping it in QA as once the build for directly showing the options for video is shown, I will move it to awaiting release

**Comment by purvi-ranawat** [comment]
It works fine now on 3.0-alpha 5
