### ISSUE TITLE
Record audio without function

### ISSUE THREAD

**Issue by orschiro** [OpenArchive/Save-app-android#43]
Dear all, 

I am very excited that I have found this app.

Thank you so much for your work!

I tried the Record audio option on my Fairphone FP1 with Android 4.2.2.

However, clicking on this option does not lead to any effect. 

What could be causing the problem?

Thankfully,

~Robert

**Comment by n8fr8** [comment]
Fairphone must not have a built in audio recorder app. We don't (yet) have our own internal audio recorder, so you should use an external one. 

There are a few more full featured ones here:
http://www.androidauthority.com/best-voice-recorder-apps-for-android-615332/

**Comment by orschiro** [comment]
Thanks Nathan!

I made sure to have a third party app installed.

It's called high q mp3 recorder.

Robert

**Comment by n8fr8** [comment]
We should offer a built-in audio recorder

**Comment by foundscapes** [comment]
+1!

On Tue, Jul 5, 2016 at 4:43 PM, Nathan Freitas <notifications@github.com>
wrote:

> We should offer a built-in audio recorder
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenArchive/openarchive/issues/43#issuecomment-230498748>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACINn5IesuqndDN1HEa0hp4TdwQMs3iFks5qSm2DgaJpZM4I3gJ4>
> .
>



-- 
“I can't understand why people are frightened of new ideas. I'm frightened
of the old ones.”

John Cage

**Comment by foundscapes** [comment]
Is this still something we're considering?

**Comment by n8fr8** [comment]
We had a built in audio recorder in OA 1.0. For 2.0, we decided that Save would not be a "capture app". Now, we've gone back on that a little with offering a capture button in the media picker, since iOS does that. Otherwise, the plan was that if a user needed to record audio, say interviews with people, they should use a dedicated app for that, off which there are many high quality fee and paid ones out there.
