### ISSUE TITLE
Implement new dropbox setup

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#435]
Dropbox setup is implemented in 2 steps:

![Dropbox - Log In](https://github.com/OpenArchive/Save-app-android/assets/1177650/b61cd335-92eb-445f-a209-bf342535df1f)
![Dropbox - Success](https://github.com/OpenArchive/Save-app-android/assets/1177650/7b1176b6-0733-4526-b960-e13cac7a2245)

Light gray dropbox text:
background: #9F9F9F;

Button typography:
```
//styleName: 16pt;
font-family: Montserrat;
font-size: 16px;
font-weight: 600;
line-height: 20px;
letter-spacing: 0.01em;
text-align: left;
```

![Icon](https://github.com/OpenArchive/Save-app-android/assets/1177650/b1b45c21-2ccc-459c-a65e-3f01614fbb16)

Figma:
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

**Comment by tladesignz** [comment]
@uniqx, since the activity is the same as in  #447, I already worked towards this, too.
However, you're definitely the one who's more knowledgable around Android styling, so I let you the progress header and the last scene and general brushing and making sure that colors work in dark mode... :-)

I'm not sure where this screenshot is coming from - as far as I saw in the Figma, the buttons are the same as with WebDAV and Internet Archive setup, so I implemented it that way.

**Comment by uniqx** [comment]
fixed by 0.3.0-alpha7

**Comment by hiromipaw** [comment]
@purvi-ranawat could you please test this?

**Comment by purvi-ranawat** [comment]
This is working fine now.

Environment : 

OS : Android 11, Android 13
Device : Samsung Galaxy A70, Samsung Galaxy A13
Build version : 0.3.0-alpha7
