### ISSUE TITLE
Implement space settings

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#447]
For dropbox:

![Dropbox](https://github.com/OpenArchive/Save-app-android/assets/1177650/04a09900-45cc-4c21-b3b3-0f9a24fed6e1)

For internet archive:

![Internet Archive](https://github.com/OpenArchive/Save-app-android/assets/1177650/702ab124-910c-4b56-9a69-95be1f3c3c3e)

For private webdav server:

![Private Server](https://github.com/OpenArchive/Save-app-android/assets/1177650/c86fc042-ede1-4f48-8efc-dc95784f6c6e)

**Comment by tladesignz** [comment]
@uniqx, when you're done with #434, #435 and #436, please revisit this and give it your last touch. Thank you!

**Comment by hiromipaw** [comment]
The new space design has changed a bit. They have changed the arrangement of the icons and the text a bit:
![Screenshot 2023-07-25 at 1 01 42 PM](https://github.com/OpenArchive/Save-app-android/assets/1177650/a9acfcaf-6a80-4a3a-8877-d20d9810d094)

**Comment by foundscapes** [comment]
to note - we are no longer using "space" to mean "server" - please use "server" going forward and not "space". thanks! @uniqx @tladesignz

**Comment by tladesignz** [comment]
Related: #489, #436.

**Comment by foundscapes** [comment]
@uniqx are these issues resolved now?

**Comment by purvi-ranawat** [comment]
@uniqx : For Internet Archive server, "Private Server" is displayed as the title instead of "Internet Archive"

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/a52432bf-86e8-4049-86d0-a14d31f96afd)


Environment : 

OS : Android 14
Device : OnePlus Nord 3 CE Lite, Samsung Galaxy A13
Build Version : 0.3.1-alpha2
