### ISSUE TITLE
Private Server Name or Private Server should be displayed in the hamburger menu instead of the whole URL

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#454]
Describe the bug : 

When we add all the three servers and expand the hamburger menu, Private Server whole URL is displayed instead of Private Server name or just "Private Server" as the title. For Dropbox and Internet Archive server, it just displays as "Dropbox" or "Internet Archive" as the title

1. Go to Save App
2. Add all the three servers
3. Go to Home Page and click on the hamburger menu

Expected behavior : 
"Private Server Name" or "Private Server" should be displayed in the hamburger menu instead of the whole URL

**Screenshots**
![image](https://github.com/OpenArchive/Save-app-android/assets/8190141/d4b4baf1-2502-4fbd-9728-ecfeb0ff1482)

**Environment 
 - OS version: Android 13
 - Device: Samsung Galaxy A13
 - App Version : 0.3.0-alpha2

**Comment by tladesignz** [comment]
Not a bug, it's a feature. Users can add WebDAV servers as many as they want. They need to be differentiated. Users can give them their own short name. If they didn't do that, the host part of the URL is displayed. The Dropbox SDK only allows one connection, that's why it just shows as "Dropbox". The Internet Archive could be used with multiple accounts. So we could think about allowing more than one here, too.
