### ISSUE TITLE
App can’t find existing folders after selecting ‘New Folder’ in the right navigation panel, then clicks ‘Browse Existing’ (or crashes)

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#474]
**Describe the bug**
App can’t find existing folders after selecting ‘New Folder’ in the right navigation panel, then clicks ‘Browse Existing’ (or crashes).

Interestingly, it does list folders created before an uninstall, as documented in #469.

**To Reproduce**
1. Create folders
2. Open right-hand side navigation panel
3. Select 'New Folder'
4. Select 'Browse Existing'
5. App can't list the existing folders, or will crash, or wil list folders created before an uninstall

**Expected behavior**
The app should show a list of actually existing folders.

**Screenshots**
![Uploading Screenshot_20230823-101333.png…]()
![Screenshot_20230823-101352](https://github.com/OpenArchive/Save-app-android/assets/4558756/8df0b904-ca3e-4a58-b1be-fb70bd7bb616)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Additional context**

**Comment by tladesignz** [comment]
Actually user confusion.

This lists already created folders **on the server**. These won't get created unless actual content is uploaded.

In a non-testing circumstance, there's most probably going to be a lot less confusion, since I assume typical users not to create lots of folders which they'll never fill but would miss after a reinstall.

Regarding the crashes: It works in general, so crashes are not reproducible. I'll look out for crash reports on the Play Store.
