### ISSUE TITLE
Already uploaded media still shows "Upload" action

### ISSUE THREAD

**Issue by onejgordon** [OpenArchive/Save-app-android#488]
**Describe the bug**

Already uploaded media still shows "Upload" action. This is confusing as it can lead user to believe their media is not in fact uploaded. It's also not clear what the upload action does in this case -- it appears to run a duplicate upload of the same file, even with no changes.

**To Reproduce**

1. Upload an image
2. From the image list, click the uploaded image, once complete
3. Choose the more menu
4. Upload action still appears and is "functional"

**Expected behavior**

Expect the upload action to be removed for uploaded content, or at least adjust the action label to clarify that uploading will replace (or whatever in fact occurs on re-upload).

**Environment (please complete the following information):**

- OS version: Android 13
- Device: Pixel 7
- App Version: 0.3.0-alpha5

**Comment by tladesignz** [comment]
This was implicitly fixed with the UI changes:
- The only thing you can do now on the main scene is delete items.
- When an item is selected, you will either jump into the "preview" scene, where you can edit metadata and start the upload, or you jump into the upload manager scene, when the item is already queued for or currently uploading. Uploaded items can only be selected for deletion.

@purvi-ranawat, this is partly published, I think, but the full correct functionality will be available in version 0.3.0-beta4, due for release on Friday, 27th.

**Comment by purvi-ranawat** [comment]
This is working fine on Version 0.3.0-beta4.
Tested on Android 11 and Android 13 on Samsung Galaxy A13, and Samsung Galaxy A70.
