### ISSUE TITLE
When connecting to Private Server it lands on the settings screen instead of the tap to add media screen

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-android#517]
Unintalled and re-installed the app to test. from the get started screens i logged in to a private server. Once connected to a private server it is supposed to take me to the my media page, but instead I land on the settings screen 

https://github.com/OpenArchive/Save-app-android/assets/145493085/6e89e2c6-a4d0-4d80-a321-c9277e087576

**Expected behavior**
After logging into the private server.i should see the screen to add media

**Screenshots**

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Moto G Pure
 - App Version 0.3.0-beta5
https://github.com/OpenArchive/Save-app-android/assets/145493085/878c7fa2-52db-4034-a430-c7e09e9d6662

**Comment by losalim** [comment]
Sorry forgot to add that i replicated the issue 2 x.

**Comment by foundscapes** [comment]
@purvi-ranawat this isn't happening for Alex or I, could you test on various platforms to see if you can reproduce? ty!

**Comment by ceylana** [comment]
@tladesignz just flagging that this happened to me when connecting to dropbox, private nexcloud server, and the Internet Archive so I don't think it is just private server related. (it wasn't happening for me in beta5 but is happening in beta6).

A few more details: Once I add a folder to a server it then allows me to go to My Media/home view, but expected behavior is to be taken to that home view first with that welcome message

Phone: Samsung Galaxy S10, Android 12
Save app version: 0.3.0-beta6

**Comment by tladesignz** [comment]
Uuups. Guess I added a regression there, recently. The problem is, when there's no folder, yet.
Sorry. 

@purvi-ranawat, will be fixed in version 0.3.0-beta7.

**Comment by foundscapes** [comment]
I did not have this problem on any of the servers, but I'm glad you are able to fix @tladesignz!

**Comment by foundscapes** [comment]
@vanichitkara please test after beta7 is released (we're on beta6 rn). thanks!

**Comment by foundscapes** [comment]
@vanichitkara this is working great for me on beta7 (just released today)! Please test when you can and close the issue if it works for you. thanks!

**Comment by foundscapes** [comment]
this is fixed in beta7
