### ISSUE TITLE
Media Compression setting is missing

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#526]
**Describe the bug**
Users should be able to specify a preference between Better Quality media, or Smaller sized media in the "General" settings but this is missing.

**To Reproduce**
1. Go to settings
2. Click on General
3. Scroll down to see that "

**Expected behavior**
I see the "Media compression" setting

**Screenshots**
**What is should look like**
![General](https://github.com/OpenArchive/Save-app-android/assets/37166640/3eb1c220-f967-4370-a044-2a36e37966db)
![Compression](https://github.com/OpenArchive/Save-app-android/assets/37166640/024ac30e-adb7-4069-9cab-4d8af5b30d0e)

**What it looks like**
![signal-2023-11-13-135034_002](https://github.com/OpenArchive/Save-app-android/assets/37166640/e8932a57-0744-4211-820d-63167062266a)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Samsung Galaxy 10
 - App Version beta 7

**Additional context**

**Comment by tladesignz** [comment]
We do not actively support reencoding of any file format. This is just for iOS videos, because iOS forces us to:

- In iOS, videos are recorded in various Apple QuickTime formats (depends on the iOS and device version), mostly Apple ProRes nowadays, I'd guess.
- That original footage cannot be loaded into an app directly. (It would be huuuuge.) Instead, one always needs to run an export.
- We use H.264 for that, as that's the most compatible one, and also typically used in most Internet settings.
- Since we export anyway, we give users a choice, as this setting can have a massive impact on the file size.
- Images and all other documents are imported as-is. As well as everything which is shared from other apps into Save. After all, we're an archiving app and want to have stuff as "oiginal" as possible.

On Android, the structure is completely different. There is nothing to chose from. We take what we get.

**Comment by ceylana** [comment]
Thanks for the explanation! This is good for us to know for training. All
good.
