### ISSUE TITLE
App crashing continuously on Android 14

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-android#528]
**Describe the bug**
One of our DAC managers is on Android 14 and the app won't stop crashing from him upon download/uninstall/download. 

**Environment (please complete the following information):**
 - OS version: Android 14
 - Device: [unknown]
 - App Version [beta 7]

**Additional context**
App in Spanish

**Comment by losalim** [comment]
David is using a Pixel 6a phone.

Adding screenshot

![signal-2023-11-14-161933](https://github.com/OpenArchive/Save-app-android/assets/145493085/70d3629c-5d16-42e6-befb-bced6b4378c8)

**Comment by uniqx** [comment]
fixed by 53248a3

**Comment by uniqx** [comment]
Starting on Android 14 foreground services require to declare additional permissions. So that's the fix I've provided. As I've just learned, Google Play has additional policy restrictions for these new permissions. They require to publishers to provide a screen capture demonstrating when the foreground service is in use. I did attempts recording such a screen capture, but I couldn't get the foreground service icon to show up. So I'll have to do more debugging and figure out what the foreground service code actually does. I have to check if it's obsolete, or needs fixing and follow up accordingly.

**Comment by uniqx** [comment]
after a little more debugging and some minor refactoring I could the foreground service to show up. That allowed me to create the video Play Console asked for submitting a new release with foreground service permission.

**Comment by foundscapes** [comment]
@vanichitkara please test, ty!

**Comment by vanichitkara** [comment]
@foundscapes I'm on Android 13 so I won't be able to test the issue on Android 14

**Comment by foundscapes** [comment]
@vanichitkara ok no worries, ty!

**Comment by foundscapes** [comment]
@purvi-ranawat please test on Android 14 ty!
