### ISSUE TITLE
Media not showing up on IA after upload

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#9]
(see Josh's response to this in Issue #14 under website)

Should we remove this feature if it can't be fixed?

![img_0229](https://cloud.githubusercontent.com/assets/2231711/15281283/8cdbd13e-1aee-11e6-8c33-8f70b8f9e147.JPG)

**Comment by n8fr8** [comment]
The issue is that we need to delay a few seconds/minutes while the archive is processing the upload. I am going to move uploads to a background process so the user doesn't have to wait, and then we'll put in a built in delay before we notify them the upload is ready. We may also be able to fetch the page in the background and check the returned content to ensure it is ready.

**Comment by foundscapes** [comment]
Sounds great!
